<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReportsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('reports')->insert([
            [
                'id' => '854b4246-c81d-4f37-b747-aed08d20cbdd',
                'report_type' => 'relief_point',
                'country_code' => 'JM',
                'parish_code' => '10',
                'community_geonames_id' => 11495062,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => 17.94805044,
                'precise_longitude' => -76.90954166,
                'location_description' => 'Ascot High School',
                'severity' => null,
                'description' => '',
                'source_url' => 'https://x.com/JamaicaObserver/status/1982916246049026237',
                'source_type' => 'social_media',
                'source_platform' => 'twitter',
                'embed_data' => '{}',
                'status' => 'unverified',
                'confirmation_count' => 1,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => 'shelter',
                'relief_point_category' => 'basic_needs',
                'contact_phone' => '+18766490529',
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => null,
                'created_at' => '2025-10-30 19:07:16',
                'updated_at' => '2025-10-30 16:33:08',
                'reporter_display' => 'Bold Green Neighbor',
            ],
            [
                'id' => '037c391e-b5a6-11f0-aee9-3cecefbe2405',
                'report_type' => 'relief_point',
                'country_code' => 'JM',
                'parish_code' => '08',
                'community_geonames_id' => 11495229,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => 18.02000000,
                'precise_longitude' => -76.80000000,
                'location_description' => null,
                'severity' => null,
                'description' => 'Red Cross distributing hot meals and water. Free for everyone.',
                'source_url' => null,
                'source_type' => null,
                'source_platform' => null,
                'embed_data' => null,
                'status' => 'community_verified',
                'confirmation_count' => 8,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => 'food_distribution',
                'relief_point_category' => 'basic_needs',
                'contact_phone' => '876-555-0101',
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => '8am - 6pm daily',
                'created_at' => '2025-10-30 08:35:04',
                'updated_at' => '2025-10-30 16:33:08',
                'reporter_display' => 'Local Volunteer',
            ],
            [
                'id' => '035d5fca-b5a6-11f0-aee9-3cecefbe2405',
                'report_type' => 'relief_point',
                'country_code' => 'JM',
                'parish_code' => '08',
                'community_geonames_id' => 11495229,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => 18.01790000,
                'precise_longitude' => -76.80990000,
                'location_description' => null,
                'severity' => null,
                'description' => 'Main Street Church opened as emergency shelter. They have cots, food, and water.',
                'source_url' => null,
                'source_type' => null,
                'source_platform' => null,
                'embed_data' => null,
                'status' => 'unverified',
                'confirmation_count' => 1,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => 'shelter',
                'relief_point_category' => 'evacuation',
                'contact_phone' => '876-555-0100',
                'capacity' => 100,
                'current_occupancy' => null,
                'operating_hours' => '24/7 during emergency',
                'created_at' => '2025-10-30 08:35:03',
                'updated_at' => '2025-10-30 16:33:08',
                'reporter_display' => 'Concerned Citizen',
            ],
            [
                'id' => '9fa3958c-591b-410d-bb36-2b0b5829d55c',
                'report_type' => 'blockage',
                'country_code' => 'JM',
                'parish_code' => '08',
                'community_geonames_id' => 11494901,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => null,
                'precise_longitude' => null,
                'location_description' => 'Arthur Wint Drive, near Bustamante Hospital for Children',
                'severity' => 'severe',
                'description' => 'A section of Arthur Wint in the vicinity of the Bustamante Hospital for Children has been blocked due to a fallen electricity pole.\n\nMotorists are being advised to use alternate routes where possible.',
                'source_url' => 'https://x.com/jamaicaobserver/status/1983282671586557954?s=46&t=FZil-rItwI07xT97Gcs6mg',
                'source_type' => 'social_media',
                'source_platform' => 'twitter',
                'embed_data' => '{}',
                'status' => 'active',
                'confirmation_count' => 1,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => null,
                'relief_point_category' => null,
                'contact_phone' => null,
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => null,
                'created_at' => '2025-10-30 07:02:27',
                'updated_at' => '2025-10-30 08:33:59',
                'reporter_display' => 'Bold Strong Phoenix',
            ],
            [
                'id' => '5d98e0b4-686e-4b6a-97b9-0b7cbbdffc94',
                'report_type' => 'damage',
                'country_code' => 'JM',
                'parish_code' => '15',
                'community_geonames_id' => 11495138,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => null,
                'precise_longitude' => null,
                'location__description' => 'Falmouth Hospital',
                'severity' => 'severe',
                'description' => 'Trelawny was among the parishes hardest hit by Hurricane Melissa on Tuesday. Parts of the Falmouth Hospital were damaged, and debris was scattered across Harbour Lane in Falmouth Square.',
                'source_url' => 'https://x.com/jamaicagleaner/status/1983725623823757774?s=46&t=FZil-rItwI07xT97Gcs6mg',
                'source_type' => 'social_media',
                'source_platform' => 'twitter',
                'embed_data' => '{"title":"Jamaica Gleaner on Twitter / X","meta":"Jamaica Gleaner","date":"","message":"","url":"https://x.com/jamaicagleaner/status/1983725623823757774?s=46&t=FZil-rItwI07xT97Gcs6mg","embed":"
","code":"
Trelawny was among the parishes hardest hit by Hurricane Melissa on Tuesday. Parts of the Falmouth Hospital were damaged, and debris was scattered across Harbour Lane in Falmouth Square. #MelissaAftermath pic.twitter.com/b58RCJsqM3
— Jamaica Gleaner (@JamaicaGleaner) October 30, 2025
\n"}',
                'status' => 'active',
                'confirmation_count' => 0,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => null,
                'relief_point_category' => null,
                'contact_phone' => null,
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => null,
                'created_at' => '2025-10-30 06:55:58',
                'updated_at' => '2025-10-30 06:55:58',
                'reporter_display' => 'Calm Swift Lion',
            ],
            [
                'id' => '6756efbd-2d78-4185-9ec6-4d5fae3702ff',
                'report_type' => 'blockage',
                'country_code' => 'JM',
                'parish_code' => '04',
                'community_geonames_id' => 11495540,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => null,
                'precise_longitude' => null,
                'location_description' => 'Nashville Road, Mandeville, Manchester',
                'severity' => 'severe',
                'description' => 'A downed utility pole is seen along Nashville Road in Mandeville, Manchester after the passage of Hurricane Melissa.',
                'source_url' => 'https://x.com/jamaicagleaner/status/1983520541047980112?s=46&t=FZil-rItwI07xT97Gcs6mg',
                'source_type' => 'social_media',
                'source_platform' => 'twitter',
                'embed_data' => '{"title":"Jamaica Gleaner on Twitter / X","meta":"Jamaica Gleaner","date":"","message":"","url":"https://x.com/jamaicagleaner/status/1983520541047980112?s=46&t=FZil-rItwI07xT97Gcs6mg","embed":"
","code":"
A downed utility pole is seen along Nashville Road in Mandeville, Manchester after the passage of Hurricane Melissa. The system wreaked havoc and caused catastrophic damage all across Jamaica. #GLNRToday #TrackingMelissa pic.twitter.com/cDQlXS8HGF
— Jamaica Gleaner (@JamaicaGleaner) October 29, 2025
\n"}',
                'status' => 'active',
                'confirmation_count' => 0,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => null,
                'relief_point_category' => null,
                'contact_phone' => null,
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => null,
                'created_at' => '2025-10-30 06:53:06',
                'updated_at' => '2025-10-30 06:53:06',
                'reporter_display' => 'Wise Quick Wolf',
            ],
            [
                'id' => '5ff2d179-66b5-417a-a385-6650f77cb679',
                'report_type' => 'damage',
                'country_code' => 'JM',
                'parish_code' => '08',
                'community_geonames_id' => 11495157,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => null,
                'precise_longitude' => null,
                'location_description' => 'Irish Town, Road to Holywell',
                'severity' => 'severe',
                'description' => '',
                'source_url' => 'https://x.com/roostersworldja/status/1983728858030600713?s=46&t=FZil-rItwI07xT97Gcs6mg',
                'source_type' => 'social_media',
                'source_platform' => 'twitter',
                'embed_data' => '{"title":"RoostersWorldja on Twitter / X","meta":"RoostersWorldja","date":"","message":"","url":"https://x.com/roostersworldja/status/1983728858030600713?s=46&t=FZil-rItwI07xT97Gcs6mg","embed":"
","code":"
I was planning on going to Holywell very soon. Wow .#HurricaneMelissa pic.twitter.com/8QlEiMW0IP
— RoostersWorldja (@RoostersWorldja) October 30, 2025
\n"}',
                'status' => 'active',
                'confirmation_count' => 0,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => null,
                'relief_point_category' => null,
                'contact_phone' => null,
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => null,
                'created_at' => '2025-10-30 06:49:24',
                'updated_at' => '2025-10-30 06:49:24',
                'reporter_display' => 'Crimson Steady Neighbor',
            ],
            [
                'id' => '950728de-17ed-4918-abd1-3c544abd8148',
                'report_type' => 'blockage',
                'country_code' => 'JM',
                'parish_code' => '09',
                'community_geonames_id' => 11495566,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => null,
                'precise_longitude' => null,
                'location_description' => 'Parry Town, Saint Ann',
                'severity' => null,
                'description' => '',
                'source_url' => 'https://x.com/giovannirdennis/status/1983288335549517892?s=46&t=FZil-rItwI07xT97Gcs6mg',
                'source_type' => 'social_media',
                'source_platform' => 'twitter',
                'embed_data' => '{}',
                'status' => 'active',
                'confirmation_count' => 0,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => null,
                'relief_point_category' => null,
                'contact_phone' => null,
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => null,
                'created_at' => '2025-10-30 05:30:25',
                'updated_at' => '2025-10-30 05:30:25',
                'reporter_display' => 'Strong Green Resident',
            ],
            [
                'id' => '02b86677-9a24-4d0e-9f7b-389663a47fc2',
                'report_type' => 'damage',
                'country_code' => 'JM',
                'parish_code' => '11',
                'community_geonames_id' => 11495102,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => null,
                'precise_longitude' => null,
                'location_description' => 'Black River, Saint Elizabeth',
                'severity' => 'critical',
                'description' => 'Before and after imagery of Black River, Jamaica.',
                'source_url' => 'https://x.com/wxnb_/status/1983630143647289414?s=46&t=FZil-rItwI07xT97Gcs6mg',
                'source_type' => 'social_media',
                'source_platform' => 'twitter',
                'embed_data' => '{"title":"Nahel Belgherze on Twitter / X","meta":"Nahel Belgherze","date":"","message":"","url":"https://x.com/wxnb_/status/1983630143647289414?s=46&t=FZil-rItwI07xT97Gcs6mg","embed":"
","code":"
Before and after imagery from Vantor (formerly Maxar) of Black River, Jamaica.Total devastation. pic.twitter.com/uYFWWMW8qP
— Nahel Belgherze (@WxNB_) October 29, 2025
\n"}',
                'status' => 'active',
                'confirmation_count' => 0,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => null,
                'relief_point_category' => null,
                'contact_phone' => null,
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => null,
                'created_at' => '2025-10-30 04:46:59',
                'updated_at' => '2025-10-30 04:46:59',
                'reporter_display' => 'Steady Strong Resident',
            ],
            [
                'id' => '1c25c528-76a1-4b31-ab3a-687b13b9fd83',
                'report_type' => 'damage',
                'country_code' => 'JM',
                'parish_code' => '11',
                'community_geonames_id' => 11495102,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => null,
                'precise_longitude' => null,
                'location_description' => 'Black River Courthouse, Saint Elizabeth',
                'severity' => 'severe',
                'description' => 'Hurricane Melissa has also destroyed the historic and national heritage site…the Black River Court House on the waterfront
Known not only to have cases but also a place showing the town’s wealth keeping town hall meetings, balls/dances and theatre plays - St. Elizabeth, Jamaica',
                'source_url' => null,
                'source_type' => null,
                'source_platform' => null,
                'embed_data' => null,
                'status' => 'active',
                'confirmation_count' => 0,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => null,
                'relief_point_category' => null,
                'contact_phone' => null,
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => null,
                'created_at' => '2025-10-30 04:41:53',
                'updated_at' => '2025-10-30 04:41:53',
                'reporter_display' => 'Gentle Calm Bear',
            ],
            [
                'id' => 'aa11c063-4c2a-48e7-8628-be61b3c86430',
                'report_type' => 'damage',
                'country_code' => 'JM',
                'parish_code' => '12',
                'community_geonames_id' => 11495091,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => null,
                'precise_longitude' => null,
                'location_description' => 'Montego Bay International Airport',
                'severity' => 'moderate',
                'description' => 'While sections of this Concourse (first pic) sustained significant damage, it only houses Gates 1-5. Because of Proximity gates 6 & 7 will also be closed out.

Gates 8-19 are on a separate Concourse (shown in second pic) which sustained minimal damage and have less repairs needed for function.',
                'source_url' => 'https://x.com/darylvazmp/status/1983640124941623499?s=46&t=FZil-rItwI07xT97Gcs6mg',
                'source_type' => 'social_media',
                'source_platform' => 'twitter',
                'embed_data' => '{"title":"darylvazmp on Twitter / X","meta":"darylvazmp","date":"","message":"","url":"https://x.com/darylvazmp/status/1983640124941623499?s=46&t=FZil-rItwI07xT97Gcs6mg","embed":"
","code":"
🚨#Update: MBJ Sangsters Intl Airport ✈️ While sections of this Concourse (first pic) sustained significant damage, it only houses Gates 1-5. Because of Proximity gates 6 & 7 will also be closed out. Gates 8-19 are on a separate Concourse (shown in second pic) which sustained… https://t.co/x4zPOeHdvj pic.twitter.com/kYEQ070UNx
— darylvazmp (@darylvazmp) October 29, 2025
\n"}',
                'status' => 'active',
                'confirmation_count' => 0,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => null,
                'relief_point_category' => null,
                'contact_phone' => null,
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => null,
                'created_at' => '2025-10-30 04:25:42',
                'updated_at' => '2025-10-30 04:25:42',
                'reporter_display' => 'Steady Crimson Resident',
            ],
            [
                'id' => '9419447b-7c3a-417b-8855-1019d07af0df',
                'report_type' => 'damage',
                'country_code' => 'JM',
                'parish_code' => '11',
                'community_geonames_id' => 11495179,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => null,
                'precise_longitude' => null,
                'location_description' => 'The Lacovia St. Thomas Anglican Church (St. Elizabeth)',
                'severity' => 'severe',
                'description' => 'The Lacovia St. Thomas Anglican Church (St. Elizabeth parish) is one of many important historical cultural and religious landmarks that have been severely damaged.',
                'source_url' => 'https://x.com/vandamcnn/status/1983670528490791088?s=46&t=FZil-rItwI07xT97Gcs6mg',
                'source_type' => 'social_media',
                'source_platform' => 'twitter',
                'embed_data' => '{"title":"Derek Van Dam on Twitter / X","meta":"Derek Van Dam","date":"","message":"","url":"https://x.com/vandamcnn/status/1983670528490791088?s=46&t=FZil-rItwI07xT97Gcs6mg","embed":"
","code":"
The Lacovia St. Thomas Anglican Church (St. Elizabeth parish) is one of many important historical cultural and religious landmarks that have been severely damaged. Our team was struck by the beauty of this building with the sun silhouetting the stained glass windows. @CNN pic.twitter.com/UI6V6dkTN4
— Derek Van Dam (@VanDamCNN) October 29, 2025
\n"}',
                'status' => 'active',
                'confirmation_count' => 0,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => null,
                'relief_point_category' => null,
                'contact_phone' => null,
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => null,
                'created_at' => '2025-10-30 04:12:11',
                'updated_at' => '2025-10-30 04:12:11',
                'reporter_display' => 'Crimson Peaceful Guardian',
            ],
            [
                'id' => '258b560f-622b-439a-8169-4962627a8fe6',
                'report_type' => 'damage',
                'country_code' => 'JM',
                'parish_code' => '16',
                'community_geonames_id' => 11494991,
                'utility_type_id' => null,
                'provider_id' => null,
                'disaster_id' => '1',
                'precise_latitude' => null,
                'precise_longitude' => null,
                'location_description' => 'White Hall, Westmoreland',
                'severity' => null,
                'description' => 'White House — Landfall point.',
                'source_url' => 'https://x.com/wxnb_/status/1983650175358042222?s=46&t=FZil-rItwI07xT97Gcs6mg',
                'source_type' => 'social_media',
                'source_platform' => 'twitter',
                'embed_data' => '{"title":"Nahel Belgherze on Twitter / X","meta":"Nahel Belgherze","date":"","message":"","url":"https://x.com/wxnb_/status/1983650175358042222?s=46&t=FZil-rItwI07xT97Gcs6mg","embed":"
","code":"
NEW: Devastating imagery from Jamaica, before & after Category 5 Hurricane Melissa. White House — Landfall point. pic.twitter.com/SUiQrOjnIb
— Nahel Belgherze (@WxNB_) October 29, 2025
\n"}',
                'status' => 'active',
                'confirmation_count' => 0,
                'comment_count' => 0,
                'upvote_count' => 0,
                'downvote_count' => 0,
                'is_flagged' => 0,
                'relief_point_type' => null,
                'relief_point_category' => null,
                'contact_phone' => null,
                'capacity' => null,
                'current_occupancy' => null,
                'operating_hours' => null,
                'created_at' => '2025-10-30 03:58:34',
                'updated_at' => '2025-10-30 03:58:34',
                'reporter_display' => 'Helpful Alert Wolf',
            ],
        ]);
    }
}
