FROM php:8.3-fpm-alpine

# Install dependencies for composer
RUN apk add --no-cache curl unzip mysql-client

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

# Copy composer files and install dependencies
COPY composer.json composer.lock ./
RUN composer install --no-dev --no-scripts --no-autoloader

# Copy the rest of the application files
COPY . .

# Run composer dump-autoload
RUN composer dump-autoload --optimize

# After copying all files, run the post-autoload-dump scripts
RUN composer run-script post-autoload-dump --no-interaction --no-dev

CMD ["php-fpm"]
