version: "3"
services:
    nginx:
        image: nginx:alpine
        container_name: open-report-map-nginx
        restart: unless-stopped
        ports:
            - "4000:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api
            - web
        networks:
            - open-report-map-network

    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        container_name: open-report-map-api
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        networks:
            - open-report-map-network

    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        container_name: open-report-map-web
        restart: unless-stopped
        ports:
            - "5173:5173"
        volumes:
            - ./:/app
        networks:
            - open-report-map-network

    mysql:
        image: "mysql/mysql-server:8.0"
        container_name: open-report-map-mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: openreportmap
            MYSQL_USER: orm
            MYSQL_PASSWORD: orm
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - open-report-map-network

networks:
    open-report-map-network:
        driver: "bridge"
