services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: open-report-map-app
    restart: unless-stopped
    ports:
      - "4000:80"
    env_file: .env.example
    volumes:
      - ./:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - mysql
    networks:
      - open-report-map-network

  mysql:
    image: mysql:8.0
    container_name: open-report-map-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: openreportmap
      MYSQL_USER: orm
      MYSQL_PASSWORD: orm
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - open-report-map-network

networks:
  open-report-map-network:
    driver: "bridge"

volumes:
  mysql-data:
