services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.api
      platforms:
        - linux/arm64
    container_name: open-report-map-app
    restart: unless-stopped
    ports:
      - "4000:80"
    env_file: .env
    volumes:
      - ./:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - mysql
    networks:
      - open-report-map-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      platforms:
        - linux/arm64
    container_name: open-report-map-api
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - mysql
    networks:
      - open-report-map-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      platforms:
        - linux/arm64
    container_name: open-report-map-web
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - open-report-map-network

  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: open-report-map-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openreportmap
      MYSQL_USER: orm
      MYSQL_PASSWORD: orm
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - open-report-map-network

networks:
  open-report-map-network:
    driver: bridge

volumes:
  mysql-data:
