# syntax=docker/dockerfile:1.6

ARG NODE_IMAGE=node:20-alpine

FROM --platform=$TARGETPLATFORM ${NODE_IMAGE}

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
